fix_seed: 0
checkpoints_every: 16
result_path: ./results_test
config_path: ./config.yaml

resume:
  resume: False
  resume_path: path/to/checkpoints.pth
  restart_optimizer: True

encoder:
  composition: esm_v2 # esm_v2, promprot, both
  model_type: esm_v2 # esm_v2, t5
  model_name:  facebook/esm2_t33_650M_UR50D # facebook/esm2_t33_650M_UR50D, facebook/esm2_t30_150M_UR50D, facebook/esm2_t12_35M_UR50D, facebook/esm2_t6_8M_UR50D, Rostlab/prot_t5_base_mt_uniref50
  max_len: 1024
  num_classes: 8
  prm4prmpro: ppi
  frag_overlap: 200

PEFT: PFT #lora # FT, PFT, frozen, lora, PromT

train_settings:
  num_epochs: 20
  shuffle: True
  device: cuda
  batch_size: 16
  grad_accumulation: 1
  loss_pos_weight: 35
  dataset: v2 # v2, v3
  fine_tune_lr: -2 # -1, -2, -3


valid_settings:
  do_every: 1
  batch_size: 16
  device: cuda


predict_settings:
  batch_size: 16
  device: cuda
  cutoffs: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

optimizer:
  name: adam
  lr: 1e-4 #-4
  weight_decouple: True
  weight_decay: 1e-3
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 1024
    min_lr: 1e-5
    gamma: 0.2
    num_restarts: 1
  mode: cosine #skip, cosine

supcon:
  apply: True
  device: cuda
  drop_out: 0.1
  n_pos: 9
  n_neg: 30
  temperature: 0.1
  hard_neg: True
  weight: 1
  warm_start: 0